romfs:
	$(ROMFSINST) bin/restclient /usr/bin/restclient
	$(ROMFSINST) lib/restclient /usr/lib/ruby/vendor_ruby/restclient
	$(ROMFSINST) lib/rest_client.rb /usr/lib/ruby/vendor_ruby/rest_client.rb
	$(ROMFSINST) lib/rest-client.rb /usr/lib/ruby/vendor_ruby/rest-client.rb
	$(ROMFSINST) lib/restclient.rb /usr/lib/ruby/vendor_ruby/restclient.rb
