#!/usr/bin/env expect

source /usr/share/3g/3g-function.exp
log_user 0

global module_type_mc8090
global module_type_hl8548

if { $argc < 1 } {
	puts "usage: $argv0 \[pid\]"
	exit 1
}

set pid [lindex $argv 0]

serial_connect 10
busy_wait 10

set module_type [get_module_type]

puts "3G disconnect"
if {$module_type == $module_type_mc8090} {
	send_command "AT!SCACT=0,$pid"
} elseif {$module_type == $module_type_hl8548} {
	send_command "AT+CGACT=0,$pid"
}
check_status 10
puts "success"

exit 0
