#!/usr/bin/env expect

source /usr/share/3g/3g-function.exp
log_user 0

global module_type_mc8090
global module_type_hl8548
set phone_num 0

serial_connect 10
busy_wait 10

set module_type [get_module_type]

send_command "AT+CNUM"
set timeout 3

if {$module_type == $module_type_mc8090} {
	expect "+CNUM: ,\""
	expect "\"," {
	    scan $expect_out(buffer) "%11s" phone_num
	}
} elseif {$module_type == $module_type_hl8548} {
	expect "+CNUM: \""
	expect "\",\""
	expect "\"," {
	    scan $expect_out(buffer) "%11s" phone_num
	}
}

check_status 1

puts "$phone_num"

exit 0
