#! /bin/sh

PRIMARY_IF=$1
MAC=`ifconfig ${PRIMARY_IF}| awk -F ' ' "/${PRIMARY_IF} /"'{print $5}'`
SERVICE_DIR=/etc/avahi/services

HTTP_SERVICE=${SERVICE_DIR}/http.service
cat > ${HTTP_SERVICE} <<EOF
<service-group>
  <name replace-wildcards="yes">http on %h [${MAC}]</name>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
  </service>
</service-group>
EOF

AT_ADMIN_SERVICE=${SERVICE_DIR}/at-admin.service
cat > ${AT_ADMIN_SERVICE} <<EOF
<service-group>
  <name replace-wildcards="yes">AT Admin on %h [${MAC}]</name>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>path=/index.cgi</txt-record>
  </service>
</service-group>
EOF

SSH_SERVICE=${SERVICE_DIR}/ssh.service.disabled
cat > ${SSH_SERVICE} <<EOF
<service-group>
  <name replace-wildcards="yes">Remote Terminal on %h [${MAC}]</name>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
  </service>
</service-group>
EOF
