#!/bin/bash

id=$1
version=$2
info=$3
config=$4

echo start script invoked: $0 $*
echo module-id=$id
echo version=$version
echo info=$info
echo config:

SHELL_API=/bin/cli-shell-api
vyatta_sbindir=/opt/vyatta/sbin

if [ "$id" = "0" ]; then
       session_env=$($SHELL_API getSessionEnv $PPID)
       eval $session_env
       $SHELL_API setupSession
       RET=`${SHELL_API} loadFile $config`
       if [ "X${RET}" = "X" ]; then
         logger -t armsd-script -p daemon.err -i "Apply configration successful."
         ${vyatta_sbindir}/my_commit
       else
         logger -t armsd-script -p daemon.err -i "Invalid configration dicarded."
         ${vyatta_sbindir}/my_discard
       fi
fi
