#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
TZ=JST-9
export PATH TZ

# Ignore CTRL-C only in this shell, so we can interrupt subprocesses.
trap ":" INT QUIT TSTP

###############################################################################
# remount /
###############################################################################
#echo "Starting fsck for root filesystem."
#mount -n -o remount,ro /

###############################################################################
# remount /
###############################################################################
echo "Remounting root rw: "
mount -n -o remount,rw /

###############################################################################
# mount proc
###############################################################################
echo "Mounting proc: "
mount -n /proc

###############################################################################
# cleaning up
###############################################################################
echo "Cleaning up system: "
cleanup_dirs="/tmp /var/lock /var/run"
rm -rf $cleanup_dirs
mkdir $cleanup_dirs

###############################################################################
# setting keepalive
###############################################################################
echo 600 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes

###############################################################################
# create issue
###############################################################################
echo "`cat /etc/DISTNAME`" > /etc/issue
echo "`cat /etc/DISTNAME`" > /etc/issue.net
echo "`uname -s` `uname -r` [`uname -m` arch]" >> /etc/issue
echo "`uname -s` `uname -r` [`uname -m` arch]" >> /etc/issue.net
echo >> /etc/issue
echo >> /etc/issue.net

###############################################################################
# change permissions
###############################################################################
echo "Changing file permissions: "
/etc/init.d/checkftp
chmod 640 /etc/shadow &&
chmod 640 /etc/gshadow &&
chmod 600 /etc/busybox.conf &&
chmod 6775 /bin/busybox &&
chown -R guest:guest /home/guest &&
chown -R 33:33 /home/www-data

###############################################################################
# setting firewall
###############################################################################
echo "Starting basic firewall: "

# set up spoofing protection
for f in /proc/sys/net/ipv4/conf/*/rp_filter
do
  echo 1 > $f
done

# log impossible addresses
for f in /proc/sys/net/ipv4/conf/*/log_martians
do
  echo 1 > $f
done

# ignore echo broadcasts
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# default setting: deny everything
iptables -F INPUT
iptables -P INPUT DROP
iptables -F OUTPUT
iptables -P OUTPUT DROP

# allow all non-external interfaces for everything
iptables -A INPUT  -i ! eth0 -j ACCEPT
iptables -A OUTPUT -o ! eth0 -j ACCEPT

# external interface
iptables -A INPUT -i eth0 -p icmp                          -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport http       -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport snmp       -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport ssh        -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport 21347      -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport ftp-data   -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport auth       -j REJECT
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport 6000:6010  -j DROP
iptables -A INPUT -i eth0 -p tcp -d 0/0 --dport 1024:65535 -j ACCEPT

iptables -A INPUT -i eth0 -p udp -d 0/0 --dport snmp       -j ACCEPT
iptables -A INPUT -i eth0 -p udp -d 0/0 --dport snmptrap   -j ACCEPT
iptables -A INPUT -i eth0 -p udp -d 0/0 --dport ssh        -j ACCEPT
iptables -A INPUT -i eth0 -p udp -d 0/0 --dport 22222      -j ACCEPT
iptables -A INPUT -i eth0 -p udp -d 0/0 --dport 1024:65535 -j ACCEPT

# all protocols outgoing
iptables -A OUTPUT -o eth0 -j ACCEPT

###############################################################################
# flatfsd
###############################################################################
echo "Loading /etc/config: "
flatfsd -r > /dev/null 2>&1

###############################################################################
# network
###############################################################################
echo "Setting up interface lo: "
ifconfig lo up 127.0.0.1

echo "Configuring network interfaces: "
discoverd &

###############################################################################
# seri2eth
###############################################################################
echo "Starting seri2eth: "
/bin/seri2eth -d /dev/ttyAM0 &

/bin/ledctrl --red=off

###############################################################################
# snmpd
###############################################################################
echo "Starting snmpd: "
snmpd -c /etc/snmp/snmpd.conf >/dev/null 2>&1

FLAG=n

###############################################################################
# sshd
###############################################################################
if [ ! -f /etc/config/ssh_host_key ] ; then
    echo "generate rsa1 key ..."
    ledctrl --red=on
    ssh-keygen -t rsa1 -f /etc/config/ssh_host_key -N '' >/dev/null
    FLAG=y
fi

if [ ! -f /etc/config/ssh_host_dsa_key ] ; then
    echo "generate dsa key ..."
    ledctrl --red=on
    ssh-keygen -t dsa -f /etc/config/ssh_host_dsa_key -N '' >/dev/null
    FLAG=y
fi

if [ ! -f /etc/config/ssh_host_rsa_key ] ; then
    echo "generate rsa key ..."
    ledctrl --red=on
    ssh-keygen -t rsa -f /etc/config/ssh_host_rsa_key -N '' >/dev/null
    FLAG=y
fi

if [ "$FLAG" = "y" ]; then
    flatfsd -s >/dev/null 2>&1
    ledctrl --red=off
fi

adduser -DH sshd >/dev/null 2>&1
mkdir -p /var/empty

echo "Stating sshd: "
/sbin/sshd -f /etc/ssh/sshd_config

###############################################################################
# rc.local
###############################################################################
LOCAL_SCRIPT=/etc/config/rc.local

if [ -x ${LOCAL_SCRIPT} ]; then
    echo "Running local start script (${LOCAL_SCRIPT})."
    ${LOCAL_SCRIPT}
fi
