#!/bin/sh

. /etc/init.d/functions

SGXDIR=/opt/firmware/sgx/linux/armhf
PATH=/bin:/sbin:/usr/bin:/usr/sbin:${SGXDIR}
export LD_LIBRARY_PATH=${SGXDIR}

echo -n "Starting PVR Server: "
pvrsrvctl --start --no-module >/dev/null 2>&1
check_status
