romfs:
	$(ROMFSINST) lib/rack-protection.rb /usr/lib/ruby/vendor_ruby/rack-protection.rb
	$(ROMFSINST) lib/rack/protection /usr/lib/ruby/vendor_ruby/rack/protection
	$(ROMFSINST) lib/rack/protection.rb /usr/lib/ruby/vendor_ruby/rack/protection.rb

