romfs:
	$(ROMFSINST) bin/fluentd /usr/bin/fluentd
	$(ROMFSINST) bin/fluent-cat /usr/bin/fluent-cat
	$(ROMFSINST) bin/fluent-debug /usr/bin/fluent-debug
	$(ROMFSINST) lib/fluent /usr/lib/ruby/vendor_ruby/fluent
	$(ROMFSINST) fluent.conf /usr/lib/ruby/fluent.conf
