#!/bin/sh

. /etc/init.d/functions

PATH=/bin:/sbin:/usr/bin:/usr/sbin
FLAG=n

if [ ! -f /etc/config/ssh_host_key ] ; then
    echo -n "generate rsa1 key ..."
    ssh-keygen -t rsa1 -f /etc/config/ssh_host_key -N '' >/dev/null
    FLAG=y
    check_status
fi

if [ ! -f /etc/config/ssh_host_dsa_key ] ; then
    echo -n "generate dsa key ..."
    ssh-keygen -t dsa -f /etc/config/ssh_host_dsa_key -N '' >/dev/null
    FLAG=y
    check_status
fi

if [ ! -f /etc/config/ssh_host_rsa_key ] ; then
    echo -n "generate rsa key ..."
    ssh-keygen -t rsa -f /etc/config/ssh_host_rsa_key -N '' >/dev/null
    FLAG=y
    check_status
fi

if [ "$FLAG" = "y" ]; then
    flatfsd -s >/dev/null 2>&1
fi

adduser -DH sshd >/dev/null 2>&1
mkdir -p /var/empty

echo -n "Starting sshd: "
/sbin/sshd -f /etc/ssh/sshd_config
check_status
