#!/bin/sh

. /etc/init.d/functions

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo -n "Setting at-cgi: "
mkdir -p /tmp/at-admin &&
chown www-data:www-data /tmp/at-admin &&
ln -s /usr/bin/ledctrl /bin/ledctrl
check_status
