.TH display 1 "Date: 2005/03/01 01:00:00" "ImageMagick"
.SH NAME
display \- displays an image or image sequence on any X server.
.SH SYNOPSIS
.TP
\fBdisplay\fP [\fIoptions\fP] \fIinput-file\fP
.SH OVERVIEW
The \fBdisplay\fP program is a member of the ImageMagick(1) suite of tools.  Use it to isplay an image or image sequence on any X server.

For more information about the display command, point your browser to file:///usr/share/doc/ImageMagick-6.2.4/www/display.html or http://www.imagemagick.org/script/display.php.

Run `display -help' to get a summary of the \fBdisplay\fP command options.
.SH SEE-ALSO
ImageMagick(1)

.SH COPYRIGHT

\fBCopyright (C) 1999-2005 ImageMagick Studio LLC. Additional copyrights and licenses apply to this software, see http://www.imagemagick.org/script/license.php\fP
