.TH "update_usbdb" "8" "0.4.8" "Shuu Yamaguchi" "Herramientas USB"
.SH "NOMBRE"
.LP 
update_usbdb \- Órden para actualizar la data que usa usbmgr
.SH "SINOPSIS"
.LP 
update_usbdb [\-dfhs] \fIfichero\fP
.SH "DESCRIPCIÓN"
.LP 
El comando \fBupdate_usbdb\fP crea la data del fichero de configuración
(como una estructura de directorio bajo \fB/etc/usbmgr/{vendor,class}\fP)
del fichero de configuración dado (usualmente \fB/etc/usbmgr/usbmgr.conf\fP).
.LP 
La estructura del directorio es como sigue:
.TP 
\fBvendor[/vendor\-ID[/product\-ID]/module]\fR
Módulo(s) a ser cargados cuando se conecta un dispositivo USB que concuerde
con el vendor.
.TP 
\fBclass[/class\-ID[/subclass\-ID[/protocol\-ID]]/module]\fR
Módulo(s) a ser cargado cuando se conecta un dispositivo USB y éste concuerda
con class.
.TP 
\fBvendor[/vendor\-ID[/product\-ID]/script]\fR
Programa a ser ejecutado cuando se (des)conecta un dispositivo USB y éste
concuerda con el vendor.
.TP 
\fBclass[/class\-ID[/subclass\-ID[/protocol\-ID]]/script]\fR
Programa a ser ejecutado cuando se (des)conecta un dispositivo USB y éste
concuerda con class.
.SH "OPCIONES"
.LP 
.TP 
\fB\-d\fR
Modo de depuración.
.TP 
\fB\-f\fR
Fuerza la actualización, aún cuando parezca no ser necesaria.
.TP 
\fB\-h\fR
Imprime ayuda \fBal syslog\fP, luego finaliza.
.TP 
\fB\-s\fR
No abre syslog en el inicio.
.SH "FICHEROS"
.LP 
\fI/etc/usbmgr/usbmgr.conf\fP
.LP 
\fI/etc/usbmgr/preload.conf\fP
.LP 
\fI/etc/usbmgr/class\fP
.LP 
\fI/etc/usbmgr/vendor\fP
.SH "VARIABLES DE ENTORNO"
.LP 
En los programas, son definidas las siguientes variables de entorno.
.TP 
\fBACTION\fR
Usted puede usar esta variable de entorno para saber si los módulos
son cargados o descargados. \fBadd\fP significa que los módulos son
cargados, y \fBremove\fP significa que los módulos son descargados.
.TP 
\fBDEVICE\fR
Apunta al fichero \fB/proc\fP del módulo (des)cargado.
.SH "EJEMPLOS"
.LP 
Para ejecutar este programa en forma estándar escriba:
.LP 
update_usbdb /etc/usbmgr/usbmgr.conf
.LP 
Se creará la jerarquía del directorio \fB/etc/usbmgr/class\fP y
\fB/etc/usbmgr/vendor\fP.
.LP 
Un ejemplo de programa de carga/descarga:
.LP 
.nf 
#!/bin/sh

case $ACTION in
add)
        echo start > /tmp/log
        chmod 666 $DEVICE
        ;;
remove)
        echo stop > /tmp/log
        chmod 644 $DEVICE
        ;;
esac
.fi 
.SH "AUTOR"
.LP 
Shuu Yamaguchi <shuu@wondernetworkresources.com>
.LP
Esta página de manual ha sido escrita por Esteban Manchado Velázquez <zoso@debian.org>, para el sistema Debian GNU/Linux (pero podría ser usada por otros).
.SH "TRADUCTOR"
.LP
Traducción de Rudy Godoy <rudy@kernel\-panik.org>.
.SH "VÉASE TAMBIÉN"
.LP 
.BR usbmgr (8),
.BR dump_usbdev (8),
.BR usbmgr.conf (5)
