#
# Automatically generated make config: don't edit
#

#
# Vendor specific
#
CONFIG_VENDOR_AUTO_LIBINSTALLER=y
CONFIG_VENDOR_AUTO_STRIPPER=y
# CONFIG_VENDOR_CHANGE_ROOT_PASSWD is not set
CONFIG_VENDOR_ROOT_PASSWD="root"
CONFIG_VENDOR_GENFS_AUTO=y
# CONFIG_VENDOR_GENFS_MANUAL is not set

#
# Applications
#
CONFIG_VENDOR_GPIOCTRL_GPIOCTRL=y
CONFIG_VENDOR_LEDCTRL_LEDCTRL=y
CONFIG_VENDOR_SWMGR_SWMGR=y
CONFIG_VENDOR_WLAN=y
# CONFIG_VENDOR_AWL12_AERIAL is not set
CONFIG_VENDOR_AWL13_AWL13=y
CONFIG_VENDOR_AWL13_AWL13_SDIO=y
# CONFIG_VENDOR_AWL13_AWL13_USB is not set
CONFIG_VENDOR_AWL13_AWL13_STA=y
CONFIG_VENDOR_AWL13_AWL13_AP=y
CONFIG_VENDOR_AWL13_AWL13_DEFAULT_STA=y
# CONFIG_VENDOR_AWL13_AWL13_DEFAULT_AP is not set

#
# Fonts
#
# CONFIG_FONTS_TAKAO is not set
# CONFIG_FONTS_VL is not set

#
# Core Applications
#
# CONFIG_USER_INIT_INIT is not set
# CONFIG_USER_INIT_CONSOLE_SH is not set
# CONFIG_USER_INIT_RUN_FIREWALL is not set
# CONFIG_USER_INIT_CONF is not set
# CONFIG_USER_SASH_SH is not set
# CONFIG_USER_SH_SH is not set
# CONFIG_USER_NWSH_SH is not set
# CONFIG_USER_BASH_BASH is not set
CONFIG_USER_OTHER_SH=y
# CONFIG_USER_SASH_REBOOT is not set
# CONFIG_USER_SASH_REBOOT_SNAPGEAR is not set
# CONFIG_USER_SASH_SHUTDOWN is not set
# CONFIG_USER_INIT_EXPAND is not set
# CONFIG_USER_VERSION_VERSION is not set
# CONFIG_USER_LOGIN_LOGIN is not set
# CONFIG_USER_OLD_PASSWORDS is not set
# CONFIG_USER_ONLY_ROOT is not set
# CONFIG_USER_AGETTY_AGETTY is not set
# CONFIG_USER_GETTYD_GETTYD is not set
# CONFIG_USER_LOGIN_PASSWD is not set
# CONFIG_USER_CRON_CRON is not set

#
# Real Time Clock
#
CONFIG_USER_HWCLOCK_HWCLOCK=y
# CONFIG_USER_RTC_M41T11 is not set
# CONFIG_USER_RTC_DS1302 is not set

#
# Vixie-cron
#
# CONFIG_USER_VIXIECRON_CRON is not set
# CONFIG_USER_VIXIECRON_CRONTAB is not set

#
# at
#
# CONFIG_USER_AT_AT is not set
# CONFIG_USER_AT_ATD is not set
# CONFIG_USER_AT_ATRUN is not set

#
# Library Configuration
#
CONFIG_BUILD_APPDEP_LIB=y

#
# Force build (Normally built when required)
#
CONFIG_LIB_LIBNET_FORCE=y
# CONFIG_LIB_FLEX_FORCE is not set
# CONFIG_LIB_LIBAES_FORCE is not set
# CONFIG_LIB_LIBDES_FORCE is not set
# CONFIG_LIB_LIBSSL_FORCE is not set
# CONFIG_LIB_LIBGMP_FORCE is not set
# CONFIG_LIB_LIBG_FORCE is not set
# CONFIG_LIB_LIBLDAP_FORCE is not set
# CONFIG_LIB_LIBPAM_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
CONFIG_LIB_ZLIB_FORCE=y
# CONFIG_LIB_LIBATM_FORCE is not set
# CONFIG_LIB_LIBPNG_FORCE is not set
# CONFIG_LIB_LIBJPEG_FORCE is not set
CONFIG_LIB_LIBSYSFS2_FORCE=y

#
# sysutils tools
#
CONFIG_LIB_LIBSYSFS2_SYSTOOL=y
CONFIG_LIB_LIBSYSFS2_GET_DEVICE=y
CONFIG_LIB_LIBSYSFS2_GET_DRIVER=y
CONFIG_LIB_LIBSYSFS2_GET_MODULE=y
# CONFIG_LIB_LIBUPNP_FORCE is not set
# CONFIG_LIB_NCURSES_FORCE is not set
# CONFIG_LIB_STLPORT is not set
# CONFIG_LIB_STLPORT_SHARED is not set
# CONFIG_LIB_EXPAT_FORCE is not set
# CONFIG_LIB_ADNS_FORCE is not set
# CONFIG_LIB_LIBCRYPT_OLD_FORCE is not set

#
# Library Configuration
#
# CONFIG_LIB_UC_LIBC_TIMEZONE is not set
CONFIG_LIB_NSS_MDNS_NSS_MDNS=y

#
# Flash Tools
#
# CONFIG_USER_FLASHW_FLASHW is not set
CONFIG_USER_NETFLASH_NETFLASH=y
CONFIG_USER_NETFLASH_WITH_FTP=y
# CONFIG_USER_NETFLASH_WITH_CGI is not set
CONFIG_USER_NETFLASH_VERSION=y
CONFIG_USER_NETFLASH_VERSION_ALLOW_CURRENT=y
# CONFIG_USER_NETFLASH_VERSION_ALLOW_OLDER is not set
# CONFIG_USER_NETFLASH_DECOMPRESS is not set
# CONFIG_USER_NETFLASH_HMACMD5 is not set
# CONFIG_USER_RECOVER_BIOS is not set
# CONFIG_USER_RECOVER_STATIC_TFTP is not set
# CONFIG_USER_RECOVER_RECOVER is not set
# CONFIG_USER_BOOTTOOLS_FLASHLOADER is not set
# CONFIG_USER_BOOTTOOLS_HIMEMLOADER is not set
# CONFIG_USER_SETMAC_SETMAC is not set

#
# MTD utils
#
CONFIG_USER_MTDUTILS=y
# CONFIG_USER_MTDUTILS_OLD is not set
CONFIG_USER_MTDUTILS_NEW=y
CONFIG_USER_MTDUTILS_FLASH_ERASE=y
CONFIG_USER_MTDUTILS_FLASH_ERASEALL=y
CONFIG_USER_MTDUTILS_FLASH_INFO=y
CONFIG_USER_MTDUTILS_FLASH_LOCK=y
CONFIG_USER_MTDUTILS_FLASH_UNLOCK=y
# CONFIG_USER_MTDUTILS_FLASH_OTP_INFO is not set
# CONFIG_USER_MTDUTILS_FLASH_OTP_DUMP is not set
# CONFIG_USER_MTDUTILS_FLASHCP is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_RFDFORMAT is not set
# CONFIG_USER_MTDUTILS_RFDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set
# CONFIG_USER_MTDUTILS_DOCFDISK is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS2 is not set
# CONFIG_USER_MTDUTILS_JFFS2DUMP is not set
# CONFIG_USER_MTDUTILS_MTD_DEBUG is not set
# CONFIG_USER_MTDUTILS_SUMTOOL is not set
# CONFIG_USER_MTDUTILS_RECV_IMAGE is not set
# CONFIG_USER_MTDUTILS_SERVE_IMAGE is not set
CONFIG_LIB_ZLIB=y

#
# Filesystem Applications
#
CONFIG_USER_FLATFSD_FLATFSD=y
# CONFIG_USER_FLATFSD_FLATFSD_OLD is not set
# CONFIG_USER_FLATFSD_3_0_1 is not set
CONFIG_USER_FLATFSD_3_0_2=y
CONFIG_USER_FLATFSD_AUTO=y
# CONFIG_USER_FLATFSD_USE_FLASH_FS is not set
# CONFIG_USER_FLATFSD_DISKLIKE is not set
# CONFIG_USER_FLATFSD_CONFIG_BLOBS is not set
CONFIG_USER_FLATFSD_COMPRESSED=y
# CONFIG_USER_FLATFSD_ENCRYPTED is not set
CONFIG_USER_FLATFSD_HAS_RTC=y
# CONFIG_USER_FLATFSD_EXTERNAL_INIT is not set
# CONFIG_USER_MOUNT_MOUNT is not set
# CONFIG_USER_MOUNT_UMOUNT is not set
# CONFIG_USER_FDISK_FDISK is not set
# CONFIG_USER_FDISK_SFDISK is not set

#
# EXT2
#
CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK=y
CONFIG_USER_E2FSPROGS_MISC_MKE2FS=y
# CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS is not set
# CONFIG_USER_E2FSPROGS_MISC_CHATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_E2LABEL is not set
CONFIG_USER_E2FSPROGS_MISC_FSCK=y
# CONFIG_USER_E2FSPROGS_MISC_LSATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND is not set
CONFIG_USER_E2FSPROGS_MISC_TUNE2FS=y
# CONFIG_USER_E2FSPROGS_MISC_UUIDGEN is not set

#
# RESIERFS
#
# CONFIG_USER_REISERFSPROGS is not set
# CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS is not set
# CONFIG_USER_REISERFSPROGS_MKREISERFS is not set
# CONFIG_USER_REISERFSPROGS_REISERFSCK is not set
# CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS is not set
# CONFIG_USER_REISERFSPROGS_UNPACK is not set

#
# MSDOS
#
CONFIG_USER_DOSFSTOOLS_DOSFSCK_DOSFSCK=y
# CONFIG_USER_DOSFSTOOLS_DOSFSLABEL_DOSFSLABEL is not set
CONFIG_USER_DOSFSTOOLS_MKDOSFS_MKDOSFS=y

#
# SAMBA
#
# CONFIG_USER_SAMBA is not set
# CONFIG_USER_SAMBA_SMBD is not set
# CONFIG_USER_SAMBA_NMBD is not set
# CONFIG_USER_SAMBA_SMBMOUNT is not set
# CONFIG_USER_SAMBA_SMBUMOUNT is not set

#
# SMBFS
#
# CONFIG_USER_SMBMOUNT_SMBMOUNT is not set
# CONFIG_USER_SMBMOUNT_SMBUMOUNT is not set

#
# CRAMFS
#
# CONFIG_USER_CRAMFS_CRAMFSCK is not set
# CONFIG_USER_CRAMFS_MKCRAMFS is not set

#
# SQUASHFS
#
# CONFIG_USER_SQUASHFSTOOLS_MKSQUASHFS is not set
# CONFIG_USER_SQUASHFSTOOLS_UNSQUASHFS is not set

#
# Network Applications
#
# CONFIG_USER_APPWEB_APPWEB is not set
# CONFIG_USER_ROUTE_ARP is not set
CONFIG_USER_AVAHI_AVAHI=y
# CONFIG_USER_FNORD_HTTPD is not set
# CONFIG_USER_BOA_SRC_BOA is not set
# CONFIG_USER_BPALOGIN_BPALOGIN is not set
# CONFIG_USER_BR2684CTL_BR2684CTL is not set
# CONFIG_USER_BRCFG_BRCFG is not set
# CONFIG_USER_BRCTL_BRCTL is not set
# CONFIG_USER_CANUTILS_CANUTILS is not set
CONFIG_USER_CURL_CURL=y
# CONFIG_USER_CURL_WITH_IDN is not set
# CONFIG_USER_CURL_WITH_LDAP is not set
# CONFIG_USER_CURL_WITH_RTMP is not set
# CONFIG_USER_CURL_WITH_SSH2 is not set
# CONFIG_USER_DHCPCD_DHCPCD is not set
# CONFIG_USER_DHCPCD_NEW_DHCPCD is not set
# CONFIG_USER_DHCPD_DHCPD is not set
# CONFIG_USER_DHCP_ISC_SERVER_DHCPD is not set
# CONFIG_USER_DHCP_ISC_CLIENT_DHCLIENT is not set
# CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY is not set
# CONFIG_USER_DIALD_DIALD is not set
# CONFIG_USER_DISCARD_DISCARD is not set
# CONFIG_USER_DISCARD_INETD_ECHO is not set
# CONFIG_USER_DISCOVERD_DISCOVERD is not set
# CONFIG_USER_DNSMASQ_DNSMASQ is not set
# CONFIG_USER_ETHATTACH_ETHATTACH is not set
CONFIG_USER_ETHTOOL_ETHTOOL=y
# CONFIG_USER_EZIPUPDATE_EZIPUPDATE is not set
# CONFIG_USER_FAKEIDENTD_IDENTD is not set
CONFIG_USER_FTP_FTP_FTP=y
CONFIG_USER_FTPD_FTPD=y
# CONFIG_USER_FREESWAN is not set
# CONFIG_USER_HTTPD_HTTPD is not set
# CONFIG_USER_HTTPTUNNEL_CLIENT is not set
# CONFIG_USER_HTTPTUNNEL_SERVER is not set
# CONFIG_USER_IFATTACH_IFATTACH is not set
# CONFIG_USER_ROUTE_IFCONFIG is not set
# CONFIG_USER_INETD_INETD is not set
# CONFIG_USER_IPCHAINS_IPCHAINS is not set
# CONFIG_USER_IPFWADM_IPFWADM is not set
# CONFIG_USER_IPMASQADM_IPMASQADM is not set
# CONFIG_USER_IPPORTFW_IPPORTFW is not set
# CONFIG_USER_IPREDIR_IPREDIR is not set
# CONFIG_USER_IPROUTE2 is not set
CONFIG_USER_IPTABLES_IPTABLES=y
# CONFIG_USER_IPTABLES_IPTABLES_1_3_6 is not set
CONFIG_USER_IPTABLES_IPTABLES_1_4_14=y
CONFIG_USER_IPTABLES_IP6TABLES=y
# CONFIG_USER_IPTABLES_AUDIT is not set
# CONFIG_USER_IPTABLES_CHECKSUM is not set
# CONFIG_USER_IPTABLES_CLASSIFY is not set
# CONFIG_USER_IPTABLES_CLUSTERIP is not set
# CONFIG_USER_IPTABLES_CONNMARK is not set
CONFIG_USER_IPTABLES_CONNSECMARK=y
# CONFIG_USER_IPTABLES_CT is not set
CONFIG_USER_IPTABLES_DNAT=y
# CONFIG_USER_IPTABLES_DSCP is not set
# CONFIG_USER_IPTABLES_ECN is not set
# CONFIG_USER_IPTABLES_IDLETIMER is not set
# CONFIG_USER_IPTABLES_LED is not set
# CONFIG_USER_IPTABLES_HL is not set
# CONFIG_USER_IPTABLES_LOG is not set
# CONFIG_USER_IPTABLES_MARK is not set
CONFIG_USER_IPTABLES_MASQUERADE=y
# CONFIG_USER_IPTABLES_MIRROR is not set
# CONFIG_USER_IPTABLES_NETMAP is not set
# CONFIG_USER_IPTABLES_NFLOG is not set
# CONFIG_USER_IPTABLES_NFQUEUE is not set
# CONFIG_USER_IPTABLES_NOTRACK is not set
# CONFIG_USER_IPTABLES_RATEEST is not set
# CONFIG_USER_IPTABLES_REDIRECT is not set
CONFIG_USER_IPTABLES_REJECT=y
# CONFIG_USER_IPTABLES_SAME is not set
CONFIG_USER_IPTABLES_SECMARK=y
# CONFIG_USER_IPTABLES_SET is not set
CONFIG_USER_IPTABLES_SNAT=y
# CONFIG_USER_IPTABLES_TCPMSS is not set
# CONFIG_USER_IPTABLES_TCPOPTSTRIP is not set
# CONFIG_USER_IPTABLES_TEE is not set
# CONFIG_USER_IPTABLES_TOS is not set
# CONFIG_USER_IPTABLES_TPROXY is not set
# CONFIG_USER_IPTABLES_TRACE is not set
# CONFIG_USER_IPTABLES_TTL is not set
# CONFIG_USER_IPTABLES_ULOG is not set
# CONFIG_USER_IPTABLES_addrtype is not set
# CONFIG_USER_IPTABLES_ah is not set
# CONFIG_USER_IPTABLES_cluster is not set
# CONFIG_USER_IPTABLES_comment is not set
# CONFIG_USER_IPTABLES_connbytes is not set
# CONFIG_USER_IPTABLES_connlimit is not set
# CONFIG_USER_IPTABLES_connmark is not set
CONFIG_USER_IPTABLES_conntrack=y
# CONFIG_USER_IPTABLES_cpu is not set
# CONFIG_USER_IPTABLES_dccp is not set
# CONFIG_USER_IPTABLES_devgroup is not set
# CONFIG_USER_IPTABLES_dscp is not set
# CONFIG_USER_IPTABLES_dst is not set
# CONFIG_USER_IPTABLES_ecn is not set
# CONFIG_USER_IPTABLES_esp is not set
# CONFIG_USER_IPTABLES_eui64 is not set
# CONFIG_USER_IPTABLES_frag is not set
# CONFIG_USER_IPTABLES_hashlimit is not set
# CONFIG_USER_IPTABLES_hbh is not set
# CONFIG_USER_IPTABLES_helper is not set
# CONFIG_USER_IPTABLES_hl is not set
CONFIG_USER_IPTABLES_icmp=y
CONFIG_USER_IPTABLES_icmp6=y
# CONFIG_USER_IPTABLES_iprange is not set
# CONFIG_USER_IPTABLES_ipv6header is not set
# CONFIG_USER_IPTABLES_ipvs is not set
# CONFIG_USER_IPTABLES_length is not set
# CONFIG_USER_IPTABLES_limit is not set
# CONFIG_USER_IPTABLES_mac is not set
# CONFIG_USER_IPTABLES_mark is not set
# CONFIG_USER_IPTABLES_mh is not set
# CONFIG_USER_IPTABLES_multiport is not set
# CONFIG_USER_IPTABLES_nfacct is not set
# CONFIG_USER_IPTABLES_osf is not set
# CONFIG_USER_IPTABLES_owner is not set
# CONFIG_USER_IPTABLES_physdev is not set
# CONFIG_USER_IPTABLES_pkttype is not set
# CONFIG_USER_IPTABLES_policy is not set
# CONFIG_USER_IPTABLES_quota is not set
# CONFIG_USER_IPTABLES_rateest is not set
# CONFIG_USER_IPTABLES_realm is not set
# CONFIG_USER_IPTABLES_recent is not set
# CONFIG_USER_IPTABLES_rpfilter is not set
# CONFIG_USER_IPTABLES_rt is not set
# CONFIG_USER_IPTABLES_sctp is not set
# CONFIG_USER_IPTABLES_set is not set
# CONFIG_USER_IPTABLES_socket is not set
CONFIG_USER_IPTABLES_standard=y
# CONFIG_USER_IPTABLES_state is not set
# CONFIG_USER_IPTABLES_statistic is not set
# CONFIG_USER_IPTABLES_string is not set
CONFIG_USER_IPTABLES_tcp=y
# CONFIG_USER_IPTABLES_tcpmss is not set
# CONFIG_USER_IPTABLES_time is not set
# CONFIG_USER_IPTABLES_tos is not set
# CONFIG_USER_IPTABLES_ttl is not set
# CONFIG_USER_IPTABLES_u32 is not set
CONFIG_USER_IPTABLES_udp=y
# CONFIG_USER_IPTABLES_unclean is not set
# CONFIG_USER_IPUTILS_IPUTILS is not set
# CONFIG_USER_KENDIN_CONFIG is not set
# CONFIG_USER_KLAXON_KLAXON is not set
# CONFIG_USER_L2TPD_L2TPD is not set
CONFIG_USER_LIGHTTPD_LIGHTTPD=y
# CONFIG_USER_LINUXIGD_LINUXIGD is not set
# CONFIG_USER_LOATTACH_LOATTACH is not set
# CONFIG_USER_LRPSTAT_LRPSTAT is not set
# CONFIG_USER_MADWIFI_TOOLS is not set
CONFIG_USER_SMTP_SMTPCLIENT=y
# CONFIG_USER_MAIL_MAIL_IP is not set
# CONFIG_USER_ROUTE_MIITOOL is not set
# CONFIG_USER_MINI_HTTPD_MINI_HTTPD is not set
# CONFIG_USER_MSNTP_MSNTP is not set
# CONFIG_USER_NESSUS_NASL is not set
# CONFIG_USER_NETCAT_NETCAT is not set
# CONFIG_USER_ROUTE_NETSTAT is not set
# CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT is not set
# CONFIG_USER_NETPIPE_NPMEMCPY is not set
# CONFIG_USER_NETPIPE_NPTCP is not set
CONFIG_USER_NTPCLIENT_NTPCLIENT=y
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
# CONFIG_USER_NTPD_NTPD is not set
# CONFIG_USER_NTPD_NTPDATE is not set
# CONFIG_USER_NTPD_NTPQ is not set
CONFIG_USER_OPENSSH=y
# CONFIG_USER_OPENSSH_VER_4_3P2 is not set
CONFIG_USER_OPENSSH_VER_6_0P1=y
CONFIG_USER_OPENSSH_SSH=y
CONFIG_USER_OPENSSH_SSHD=y
# CONFIG_USER_OPENSSH_SFTPSERVER is not set
# CONFIG_USER_OPENSSH_SSHKEYSIGN is not set
CONFIG_USER_OPENSSH_SSHKEYGEN=y
# CONFIG_USER_OPENSSH_SSHKEYSCAN is not set
# CONFIG_USER_OPENSSH_SSHVULNKEY is not set
# CONFIG_USER_OPENSSH_SSHAGENT is not set
# CONFIG_USER_OPENSSH_SSHPKCS11 is not set
# CONFIG_USER_OPENSSH_SSHADD is not set
# CONFIG_USER_OPENSSH_SFTP is not set
# CONFIG_USER_OPENSSH_SCP is not set
# CONFIG_USER_OPENSSL_APPS is not set
CONFIG_USER_PING_PING=y
# CONFIG_USER_PLUG_PLUG is not set
# CONFIG_USER_PORTMAP_PORTMAP is not set
CONFIG_USER_PPPD_PPPD_PPPD=y
# CONFIG_USER_PPTPD_PPTPCTRL is not set
# CONFIG_USER_PPTPD_PPTPD is not set
# CONFIG_USER_PPTP_CLIENT_PPTP is not set
# CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR is not set
# CONFIG_USER_RDATE_RDATE is not set
# CONFIG_USER_ROUTE_ROUTE is not set
# CONFIG_USER_ROUTED_ROUTED is not set
# CONFIG_USER_RP_PPPOE_PPPOE is not set
# CONFIG_USER_RP_PPPOE_PPPOE_SERVER is not set
# CONFIG_USER_RSYSLOGD_RSYSLOGD is not set
# CONFIG_USER_SER_SER is not set
# CONFIG_USER_SERI2ETH_SERI2ETH is not set
# CONFIG_USER_SETHDLC_SETHDLC is not set
# CONFIG_USER_SLATTACH_SLATTACH is not set
# CONFIG_USER_SNMPD_SNMPD is not set
# CONFIG_USER_SNORT_SNORT is not set
# CONFIG_USER_SPEEDTOUCH_MODEM_RUN is not set
# CONFIG_USER_STUNNEL_STUNNEL is not set
# CONFIG_USER_SSLWRAP_SSLWRAP is not set
# CONFIG_USER_SQUID_SQUID is not set
# CONFIG_USER_SSH_SSH is not set
# CONFIG_USER_SSH_SSHD is not set
# CONFIG_USER_SSH_SSHKEYGEN is not set
# CONFIG_USER_STP_STP is not set
# CONFIG_USER_TCPWRAP_TCPD is not set
# CONFIG_USER_TCPBLAST_TCPBLAST is not set
# CONFIG_USER_TCPDUMP_TCPDUMP is not set
# CONFIG_USER_TELNETD_TELNETD is not set
# CONFIG_USER_TELNET_TELNET is not set
CONFIG_USER_TFTP_TFTP=y
# CONFIG_USER_TFTPD_TFTPD is not set
# CONFIG_USER_THTTPD_THTTPD is not set
CONFIG_USER_THTTPD_HTPASSWD=y
# CONFIG_USER_TRACEROUTE_TRACEROUTE is not set
# CONFIG_USER_UCDSNMP is not set
# CONFIG_USER_VCONFIG_VCONFIG is not set
# CONFIG_USER_VPNLED_VPNLED is not set
CONFIG_USER_WGET=y
CONFIG_USER_ZCIP_ZCIP=y
# CONFIG_USER_ZEBRA_ZEBRA_ZEBRA is not set

#
# Net-tools
#
# CONFIG_USER_NET_TOOLS_ARP is not set
# CONFIG_USER_NET_TOOLS_HOSTNAME is not set
# CONFIG_USER_NET_TOOLS_IFCONFIG is not set
# CONFIG_USER_NET_TOOLS_NAMEIF is not set
# CONFIG_USER_NET_TOOLS_NETSTAT is not set
# CONFIG_USER_NET_TOOLS_PLIPCONFIG is not set
# CONFIG_USER_NET_TOOLS_RARP is not set
# CONFIG_USER_NET_TOOLS_ROUTE is not set
# CONFIG_USER_NET_TOOLS_SLATTACH is not set
# CONFIG_USER_NET_TOOLS_MII_TOOL is not set

#
# Wireless-tools
#
CONFIG_USER_WIRELESS_TOOLS=y
# CONFIG_USER_WIRELESS_TOOLS_IFRENAME is not set
CONFIG_USER_WIRELESS_TOOLS_IWCONFIG=y
# CONFIG_USER_WIRELESS_TOOLS_IWEVENT is not set
# CONFIG_USER_WIRELESS_TOOLS_IWGETID is not set
CONFIG_USER_WIRELESS_TOOLS_IWLIST=y
CONFIG_USER_WIRELESS_TOOLS_IWPRIV=y
# CONFIG_USER_WIRELESS_TOOLS_IWSPY is not set
# CONFIG_USER_HOSTAP_HOSTAP is not set
# CONFIG_USER_WLAN_NG is not set

#
# Miscellaneous Applications
#
# CONFIG_USER_A500FXDEMO_A500FXDEMO is not set
# CONFIG_USER_LANG_A60 is not set
# CONFIG_USER_ARMSD is not set
CONFIG_USER_AT_CGI=y
# CONFIG_USER_AT_CGI_TOPONLY is not set
CONFIG_USER_AT_CGI_SYSTEM=y
# CONFIG_USER_AT_CGI_FIREWALL is not set
# CONFIG_USER_AT_CGI_BRIDGE is not set
# CONFIG_USER_AT_CGI_USBDATA is not set
# CONFIG_USER_AT_CGI_PACKETSCAN is not set
# CONFIG_USER_CAL_CAL is not set
# CONFIG_USER_CHAT_CHAT is not set
# CONFIG_USER_CKSUM_CKSUM is not set
# CONFIG_USER_CLOCK_CLOCK is not set
# CONFIG_USER_CPU_CPU is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOTEST is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOKEYTEST is not set
# CONFIG_USER_CAL_DATE is not set
# CONFIG_USER_DHRYSTONE_DHRYSTONE is not set
# CONFIG_USER_DE2TSCAL_DE2TSCAL is not set
CONFIG_USER_EVTEST_EVTEST=y
# CONFIG_USER_EXPAT_EXAMPLES is not set
CONFIG_USER_EXPECT_EXPECT=y
# CONFIG_USER_FROB_LED_FROB_LED is not set
# CONFIG_USER_GDBSERVER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER_GDBSERVER is not set
# CONFIG_USER_GREP_GREP is not set
# CONFIG_USER_HD_HD is not set
# CONFIG_USER_I2CTOOLS is not set
# CONFIG_USER_JAVA is not set
# CONFIG_USER_LCD_LCD is not set
# CONFIG_USER_LEDCON_LEDCON is not set
# CONFIG_USER_LILO_LILO is not set
# CONFIG_USER_LISSA_LISSA is not set
# CONFIG_USER_LPR is not set
# CONFIG_USER_LUA_LUA is not set
# CONFIG_USER_USBCBI_USBCBI is not set
# CONFIG_USER_USBISO_USBISO is not set
# CONFIG_USER_MATH_TEST is not set
# CONFIG_USER_MAWK_AWK is not set
# CONFIG_USER_MOSQUITTO_MOSQUITTO_CLIENT is not set
# CONFIG_USER_NULL_NULL is not set
# CONFIG_USER_PALMBOT_PALMBOT is not set
# CONFIG_USER_PCMCIA_CS is not set
# CONFIG_USER_PCMCIAUTILS is not set
# CONFIG_USER_PERL_PERL is not set
# CONFIG_USER_PYTHON_PYTHON is not set
# CONFIG_USER_READPROFILE_READPROFILE is not set
# CONFIG_USER_ROOTLOADER_ROOTLOADER is not set
# CONFIG_USER_RTNOTIFYD is not set
# CONFIG_USER_RUBY_RUBY is not set
# CONFIG_USER_SETSERIAL_SETSERIAL is not set
# CONFIG_USER_TRIPWIRE_SIGGEN is not set
# CONFIG_USER_STRACE_STRACE is not set
# CONFIG_USER_STTY_STTY is not set
CONFIG_USER_SUDO=y
# CONFIG_USER_TCSH_TCSH is not set
# CONFIG_USER_TINYTCL_TCLSH is not set
# CONFIG_USER_THREADDEMOS_THREADDEMOS is not set
CONFIG_USER_TIP_TIP=y
# CONFIG_USER_TRIPWIRE_TRIPWIRE is not set
# CONFIG_USER_TSLIBUTILS is not set
CONFIG_USER_UDEV=y
# CONFIG_USER_UDEV_105 is not set
CONFIG_USER_UDEV_175=y
# CONFIG_USER_UDEV_DEFAULT_SCRIPT_CONF is not set
CONFIG_USER_UDEV_DEFAULT_RULES=y
CONFIG_USER_UDEV_EXTRAS_ACCELEROMETER=y
CONFIG_USER_UDEV_EXTRAS_ATA_ID=y
CONFIG_USER_UDEV_EXTRAS_CDROM_ID=y
CONFIG_USER_UDEV_EXTRAS_COLLECT=y
CONFIG_USER_UDEV_EXTRAS_FIRMWARE=y
CONFIG_USER_UDEV_EXTRAS_MTD_PROBE=y
# CONFIG_USER_UDEV_EXTRAS_RULE_GENERATOR is not set
CONFIG_USER_UDEV_EXTRAS_SCSI_ID=y
CONFIG_USER_UDEV_EXTRAS_UDEV_ACL=y
CONFIG_USER_UDEV_EXTRAS_USB_DB=y
CONFIG_USER_UDEV_EXTRAS_V4L_ID=y
# CONFIG_USER_USBMGR is not set
# CONFIG_USER_WATCHDOG_WATCHDOG is not set
CONFIG_USER_LRZSZ_LRZSZ=y
CONFIG_USER_LRZSZ_LRZ=y
CONFIG_USER_LRZSZ_LSZ=y

#
# LIRC
#
# CONFIG_USER_LIRC is not set
# CONFIG_USER_LIRC_LIRCD is not set
# CONFIG_USER_LIRC_IRRECORD is not set
# CONFIG_USER_LIRC_LIRCMD is not set
# CONFIG_USER_LIRC_IREXEC is not set
# CONFIG_USER_LIRC_IRW is not set
# CONFIG_USER_LIRC_MODE2 is not set

#
# Editors
#
CONFIG_USER_JOE_JOE=y
# CONFIG_USER_LEVEE_VI is not set
# CONFIG_USER_ELVISTINY_VI is not set

#
# Multimedia tools
#
# CONFIG_USER_GSTREAMER_1_0 is not set
# CONFIG_USER_GSTREAMER_0_10 is not set

#
# Audio tools
#
CONFIG_USER_ALSAUTILS=y
CONFIG_USER_ALSAUTILS_APLAY=y
CONFIG_USER_ALSAUTILS_AMIXER=y
CONFIG_USER_ALSAUTILS_ARECORD=y
# CONFIG_USER_BPLAY_BPLAY is not set
# CONFIG_USER_MP3PLAY_MP3PLAY is not set
# CONFIG_USER_OGGPLAY_OGG123 is not set
# CONFIG_USER_OGGPLAY_EXAMPLE is not set
# CONFIG_USER_MUSICBOX_MUSICBOX is not set
# CONFIG_USER_PLAY_PLAY is not set
# CONFIG_USER_PLAY_TONE is not set
# CONFIG_USER_VPLAY_VPLAY is not set
# CONFIG_USER_VPLAY_VREC is not set
# CONFIG_USER_VPLAY_MIXER is not set
# CONFIG_USER_PLAYRT_PLAYRT is not set

#
# Graphics tools
#
# CONFIG_USER_IMAGEMAGICK is not set

#
# Video tools
#
# CONFIG_USER_CAMCTRL is not set
# CONFIG_USER_CAMSERV is not set
# CONFIG_USER_FBGRAB_FBGRAB is not set
CONFIG_USER_MJPGSTREAMER=y
# CONFIG_USER_MJPGSTREAMER94_MJPGSTREAMER is not set
CONFIG_USER_MJPGSTREAMER182_MJPGSTREAMER=y
# CONFIG_USER_UVCGADGET_UVCGADGET is not set
# CONFIG_USER_V4LUTILS_V4L2COMPLIANCE is not set
CONFIG_USER_V4LUTILS_V4L2CTL=y
# CONFIG_USER_V4LUTILS_V4L2DBG is not set
# CONFIG_USER_W3CAM_VIDCAT is not set
# CONFIG_USER_W3CAM_W3CAMD is not set

#
# Fileutils tools
#
# CONFIG_USER_FILEUTILS_CAT is not set
# CONFIG_USER_FILEUTILS_CHGRP is not set
# CONFIG_USER_FILEUTILS_CHMOD is not set
# CONFIG_USER_FILEUTILS_CHOWN is not set
# CONFIG_USER_FILEUTILS_CMP is not set
# CONFIG_USER_FILEUTILS_CP is not set
# CONFIG_USER_FILEUTILS_DD is not set
# CONFIG_USER_FILEUTILS_GREP is not set
# CONFIG_USER_FILEUTILS_L is not set
# CONFIG_USER_FILEUTILS_LN is not set
# CONFIG_USER_FILEUTILS_LS is not set
# CONFIG_USER_FILEUTILS_MKDIR is not set
# CONFIG_USER_FILEUTILS_MKFIFO is not set
# CONFIG_USER_FILEUTILS_MKNOD is not set
# CONFIG_USER_FILEUTILS_MORE is not set
# CONFIG_USER_FILEUTILS_MV is not set
# CONFIG_USER_FILEUTILS_RM is not set
# CONFIG_USER_FILEUTILS_RMDIR is not set
# CONFIG_USER_FILEUTILS_SYNC is not set
# CONFIG_USER_FILEUTILS_TOUCH is not set

#
# Shutils tools
#
# CONFIG_USER_SHUTILS_BASENAME is not set
# CONFIG_USER_SHUTILS_DATE is not set
# CONFIG_USER_SHUTILS_DIRNAME is not set
# CONFIG_USER_SHUTILS_ECHO is not set
# CONFIG_USER_SHUTILS_FALSE is not set
# CONFIG_USER_SHUTILS_LOGNAME is not set
# CONFIG_USER_SHUTILS_PRINTENV is not set
# CONFIG_USER_SHUTILS_PWD is not set
# CONFIG_USER_SHUTILS_TRUE is not set
# CONFIG_USER_SHUTILS_UNAME is not set
# CONFIG_USER_SHUTILS_WHICH is not set
# CONFIG_USER_SHUTILS_WHOAMI is not set
# CONFIG_USER_SHUTILS_YES is not set

#
# Sysutils tools
#
# CONFIG_USER_SYSUTILS_REBOOT is not set
# CONFIG_USER_SYSUTILS_SHUTDOWN is not set
# CONFIG_USER_SYSUTILS_DF is not set
# CONFIG_USER_SYSUTILS_FREE is not set
# CONFIG_USER_SYSUTILS_HOSTNAME is not set
# CONFIG_USER_SYSUTILS_KILL is not set
# CONFIG_USER_SYSUTILS_PS is not set

#
# Procps tools
#
# CONFIG_USER_PROCPS_FREE is not set
# CONFIG_USER_PROCPS_KILL is not set
# CONFIG_USER_PROCPS_PGREP is not set
# CONFIG_USER_PROCPS_PKILL is not set
# CONFIG_USER_PROCPS_PMAP is not set
# CONFIG_USER_PROCPS_PS is not set
# CONFIG_USER_PROCPS_PWDX is not set
# CONFIG_USER_PROCPS_SKILL is not set
# CONFIG_USER_PROCPS_SLABTOP is not set
# CONFIG_USER_PROCPS_SNICE is not set
# CONFIG_USER_PROCPS_SYSCTL is not set
# CONFIG_USER_PROCPS_TLOAD is not set
# CONFIG_USER_PROCPS_TOP is not set
# CONFIG_USER_PROCPS_UPTIME is not set
# CONFIG_USER_PROCPS_VMSTAT is not set
# CONFIG_USER_PROCPS_W is not set
# CONFIG_USER_PROCPS_WATCH is not set

#
# PCI utilities
#
# CONFIG_USER_PCIUTILS_LSPCI is not set
# CONFIG_USER_PCIUTILS_SETPCI is not set

#
# 
#
# CONFIG_USER_CXXTEST_CXXTEST is not set

#
# BusyBox
#
CONFIG_USER_BUSYBOX_BUSYBOX=y
# CONFIG_USER_BUSYBOX_1_00_RC3 is not set
CONFIG_USER_BUSYBOX_1_20_2=y

#
# Configuration menu
#

#
# Tinylogin
#
# CONFIG_USER_TINYLOGIN_TINYLOGIN is not set

#
# Qt
#

#
# X Window System
#
# CONFIG_USER_XSERVER_KDRIVE is not set

#
# MicroWindows
#
# CONFIG_USER_MICROWIN is not set

#
# Games
#
# CONFIG_USER_GAMES_ADVENT4 is not set
# CONFIG_USER_GAMES_DUNGEON is not set
# CONFIG_USER_GAMES_RUBIK is not set

#
# Miscellaneous Configuration
#
CONFIG_USER_RAMIMAGE_NONE=y
# CONFIG_USER_RAMIMAGE_RAMFS64 is not set
# CONFIG_USER_RAMIMAGE_RAMFS128 is not set
# CONFIG_USER_RAMIMAGE_RAMFS256 is not set
# CONFIG_USER_RAMIMAGE_RAMFS512 is not set
# CONFIG_USER_RAMIMAGE_RAMFS1024 is not set
# CONFIG_USER_RAMIMAGE_RAMFS2048 is not set
# CONFIG_USER_RAMIMAGE_RAMFS8192 is not set
# CONFIG_USER_CGI_GENERIC is not set
# CONFIG_USER_CGIHTML is not set
# CONFIG_USER_DEMO_BUTTON is not set
# CONFIG_USER_DEMO_LATCH is not set
# CONFIG_USER_DEMO_MORSE is not set
# CONFIG_USER_DEMO_R2100 is not set

#
# Debug Builds
#
# CONFIG_LIB_DEBUG is not set
# CONFIG_USER_DEBUG is not set

#
# Debug tools
#
# CONFIG_USER_TIMEPEG_TPT is not set

#
# Debug libraries
#
# CONFIG_LIB_LIBCCMALLOC is not set
