romfs:
	$(ROMFSINST) bin/httpclient /usr/bin/httpclient
	$(ROMFSINST) lib/httpclient /usr/lib/ruby/vendor_ruby/httpclient
	$(ROMFSINST) lib/http-access2 /usr/lib/ruby/vendor_ruby/http-access2
	$(ROMFSINST) lib/hexdump.rb /usr/lib/ruby/vendor_ruby/hexdump.rb
	$(ROMFSINST) lib/http-access2.rb /usr/lib/ruby/vendor_ruby/http-access2.rb
	$(ROMFSINST) lib/httpclient.rb /usr/lib/ruby/vendor_ruby/httpclient.rb
	$(ROMFSINST) lib/oauthclient.rb /usr/lib/ruby/vendor_ruby/oauthclient.rb
